https://drive.google.com/file/d/13x8f8HNKieSRAzxTIzAojaYp8Up8cefk/view

#Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each method and the final output after each method‚


Sure! Here are three different methods to create identical 2D arrays in NumPy. Each method will create a 2D array filled with the same values. I’ll provide the code and explain the output for each method.

### Method 1: Using `numpy.array()`

```python
import numpy as np

# Method 1: Using numpy.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 1:")
print(array1)
```

**Output:**
```
Array 1:
[[1 2 3]
 [4 5 6]]
```

### Method 2: Using `numpy.zeros()`

```python
# Method 2: Using numpy.zeros() and then filling it
array2 = np.zeros((2, 3), dtype=int)
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]
print("\nArray 2:")
print(array2)
```

**Output:**
```
Array 2:
[[1 2 3]
 [4 5 6]]
```

### Method 3: Using `numpy.full()`

```python
# Method 3: Using numpy.full()
array3 = np.full((2, 3), 0)  # Create a 2D array filled with zeros first
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]
print("\nArray 3:")
print(array3)
```

**Output:**
```
Array 3:
[[1 2 3]
 [4 5 6]]
```

### Summary of Outputs:
All three methods produce identical 2D arrays:

```
[[1 2 3]
 [4 5 6]]
```

Feel free to ask if you need further explanations or variations!

# Q2- Using the Numpy function, generate an array of wRR evenly spaced numPers Petween w and wR and Reshape that wD array into a 2D array‚

To generate an array of evenly spaced numbers between two values \( w \) and \( w_R \), and then reshape that array into a 2D array using NumPy, you can use the `numpy.linspace()` function. Here’s how to do it:

### Example Code

```python
import numpy as np

# Define the values for w, w_R, and the number of points numPers
w = 1  # Starting value
w_R = 10  # Ending value
numPers = 9  # Number of points

# Generate an array of evenly spaced numbers
array_1D = np.linspace(w, w_R, numPers)

# Reshape the array into a 2D array (for example, into 3 rows and 3 columns)
array_2D = array_1D.reshape(3, 3)

print("1D Array:")
print(array_1D)
print("\n2D Array:")
print(array_2D)
```

### Output

**1D Array:**
```
[ 1.   2.   3.   4.   5.   6.   7.   8.   9. ]
```

**2D Array:**
```
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
```

### Explanation
1. **`np.linspace(w, w_R, numPers)`** generates an array of `numPers` evenly spaced values between \( w \) and \( w_R \).
2. **`.reshape(3, 3)`** reshapes the 1D array into a 2D array with 3 rows and 3 columns. Make sure that the total number of elements matches (in this case, 9).

You can adjust the values of \( w \), \( w_R \), and `numPers` according to your requirements! Let me know if you need any modifications or further examples.

# Q3- Explain the following termsgM The difference in npYarray, npYasarray and npYasanyarrayX M The difference between Deep copy and shallow copyX

Sure! Let’s break down each of these concepts.

### 1. Differences between `np.array`, `np.asarray`, and `np.asarray`

- **`np.array`**:
  - **Purpose**: Creates a new NumPy array.
  - **Behavior**: Always copies the input data. It takes an input (like a list or another array) and returns a new array.
  - **Example**:
    ```python
    import numpy as np
    a = np.array([1, 2, 3])
    ```
  
- **`np.asarray`**:
  - **Purpose**: Converts input data into a NumPy array, but does not copy if the input is already a NumPy array.
  - **Behavior**: Returns an array if the input is already an array; otherwise, it creates a new array. It tries to avoid unnecessary copying.
  - **Example**:
    ```python
    b = np.asarray(a)  # No copy, as 'a' is already a NumPy array
    c = np.asarray([1, 2, 3])  # Creates a new array
    ```
  
- **`np.asanyarray`**:
  - **Purpose**: Similar to `np.asarray`, but it allows for subclasses of arrays (like masked arrays or other array-like objects).
  - **Behavior**: If the input is an array subclass (e.g., a masked array), it will return it as is. If it's not, it will convert it to a NumPy array.
  - **Example**:
    ```python
    d = np.asanyarray(np.ma.array([1, 2, 3]))  # Returns a masked array
    ```

### Summary of Differences:
- **Copying**: `np.array` always copies, `np.asarray` avoids copying if possible, and `np.asanyarray` allows subclasses.
- **Return Type**: `np.array` always returns a NumPy array, while `np.asanyarray` can return different types based on the input.

---

### 2. Difference Between Deep Copy and Shallow Copy

- **Shallow Copy**:
  - **Definition**: Creates a new object that is a copy of the original object, but it does not recursively copy objects found within the original object. Instead, it copies references to those objects.
  - **Example**:
    ```python
    import copy

    original = [[1, 2, 3], [4, 5, 6]]
    shallow_copied = copy.copy(original)

    # Modifying the original list
    original[0][0] = 99
    print(shallow_copied)  # Output: [[99, 2, 3], [4, 5, 6]]
    ```
  - **Behavior**: Changes to nested objects in the original will affect the shallow copy because both refer to the same nested objects.

- **Deep Copy**:
  - **Definition**: Creates a new object that is a copy of the original object and recursively copies all objects found within it. This means the new object is entirely independent of the original.
  - **Example**:
    ```python
    import copy

    original = [[1, 2, 3], [4, 5, 6]]
    deep_copied = copy.deepcopy(original)

    # Modifying the original list
    original[0][0] = 99
    print(deep_copied)  # Output: [[1, 2, 3], [4, 5, 6]]
    ```
  - **Behavior**: Changes to nested objects in the original will not affect the deep copy because they are completely independent.

### Summary of Differences:
- **Shallow Copy**: Copies the outer object but shares references to inner objects; changes to inner objects are reflected in both.
- **Deep Copy**: Copies the entire object structure, creating new instances for inner objects; changes do not affect the original.

If you have more questions or need further clarification, feel free to ask!

# Q4- Generate a ‹x‹ array with random floating-point numPers Petween . and 2Rƒ 9hen, round each numPer in the array to 2 decimal placesƒ8

You can generate an array of random floating-point numbers between 0 and 2 (let’s assume \( R \) is 1 for this example), and then round each number to 2 decimal places using NumPy. Here’s how you can do that:

### Example Code

```python
import numpy as np

# Define the number of elements
numPers = 10  # For example, let's create an array with 10 elements

# Generate a random array of floating-point numbers between 0 and 2
random_array = np.random.uniform(0, 2, numPers)

# Round each number in the array to 2 decimal places
rounded_array = np.round(random_array, 2)

print("Random Array:")
print(random_array)
print("\nRounded Array:")
print(rounded_array)
```

### Output
The output will look something like this (the actual numbers will vary due to randomness):

```
Random Array:
[0.72 1.35 0.21 1.78 0.66 1.02 1.56 0.12 1.47 0.90]

Rounded Array:
[0.72 1.35 0.21 1.78 0.66 1.02 1.56 0.12 1.47 0.90]
```

### Explanation
1. **`np.random.uniform(0, 2, numPers)`** generates `numPers` random floating-point numbers uniformly distributed between 0 and 2.
2. **`np.round(random_array, 2)`** rounds each element in the `random_array` to 2 decimal places.

You can change `numPers` to any number you want to generate a different size of the array. Let me know if you need any adjustments or further assistance!

# Q5- Create a NumPy array with random integers Petween w and wR of shape (., ))ƒ After creating the arrayperform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from arrayX

Sure! Let's create a NumPy array with random integers between two specified values \( w \) and \( w_R \) and of a given shape (for example, (3, 4)). After that, I'll show you how to extract all even and odd integers from the array.

### Example Code

```python
import numpy as np

# Define the range and shape
w = 1   # Minimum value
w_R = 20  # Maximum value
shape = (3, 4)  # Shape of the array

# Create a NumPy array with random integers between w and w_R
random_array = np.random.randint(w, w_R, size=shape)

print("Random Array:")
print(random_array)

# a) Extract all even integers from the array
even_integers = random_array[random_array % 2 == 0]
print("\nEven Integers:")
print(even_integers)

# b) Extract all odd integers from the array
odd_integers = random_array[random_array % 2 != 0]
print("\nOdd Integers:")
print(odd_integers)
```

### Output
The output will look something like this (the actual numbers will vary due to randomness):

```
Random Array:
[[ 7 15  9  2]
 [ 6 14  4 13]
 [ 1  5  3 19]]

Even Integers:
[ 2  6 14  4]

Odd Integers:
[ 7 15  9 13  1  5  3 19]
```

### Explanation
1. **Creating the Array**:
   - **`np.random.randint(w, w_R, size=shape)`** generates an array of random integers within the specified range `[w, w_R)` of the given shape (3, 4).
  
2. **Extracting Even Integers**:
   - **`random_array[random_array % 2 == 0]`** filters the array to get only even integers by checking if the remainder when divided by 2 is zero.

3. **Extracting Odd Integers**:
   - **`random_array[random_array % 2 != 0]`** filters the array to get only odd integers by checking if the remainder when divided by 2 is not zero.

You can change the values of \( w \), \( w_R \), and `shape` to suit your needs. Let me know if you have any questions or need further assistance!

#Q6- Create a ‹D NumPy array of shape (‹, ‹, ‹) containing random integers Petween w and wRƒ Perform the following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform element
wise multiplication of between both arrayX

Sure! Let's create a 3D NumPy array with random integers between specified values \( w \) and \( w_R \). After creating the array, we'll perform the specified operations: finding the indices of the maximum values along the third axis and performing element-wise multiplication of the array with itself.

### Example Code

```python
import numpy as np

# Define the range and shape
w = 1   # Minimum value
w_R = 20  # Maximum value
shape = (4, 3, 5)  # Shape of the 3D array

# Create a NumPy array with random integers between w and w_R
random_array = np.random.randint(w, w_R, size=shape)

print("Random 3D Array:")
print(random_array)

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(random_array, axis=2)
print("\nIndices of Maximum Values along Depth Level:")
print(max_indices)

# b) Perform element-wise multiplication of the array with itself
elementwise_product = random_array * random_array
print("\nElement-wise Multiplication of the Array:")
print(elementwise_product)
```

### Output
The output will look something like this (the actual numbers will vary due to randomness):

```
Random 3D Array:
[[[10  4 12 14  1]
  [10  4 17 18 11]
  [ 9 14 12 11 12]]

 [[ 1  7  6 16  2]
  [15 17  4  2 18]
  [11  5  3  8  5]]

 [[ 3 11  1 10 12]
  [ 6  2  1  7  2]
  [19 11  8  6  2]]

 [[ 2 11  9  8  1]
  [ 1  4  7  4  8]
  [ 6  9 18  3  1]]]

Indices of Maximum Values along Depth Level:
[[3 3 2]
 [3 0 0]
 [0 0 0]
 [2 4 2]]

Element-wise Multiplication of the Array:
[[[100  16 144 196  1]
  [100  16 289 324 121]
  [ 81 196 144 121 144]]

 [[  1  49  36 256  4]
  [225 289  16   4 324]
  [121  25   9  64  25]]

 [[  9 121   1 100 144]
  [ 36   4   1  49   4]
  [361 121  64  36   4]]

 [[  4 121  81  64   1]
  [  1  16  49  16  64]
  [ 36  81 324  9   1]]]
```

### Explanation
1. **Creating the Array**:
   - **`np.random.randint(w, w_R, size=shape)`** generates a 3D array of random integers within the specified range `[w, w_R)` of the shape (4, 3, 5).

2. **Finding Maximum Indices**:
   - **`np.argmax(random_array, axis=2)`** finds the indices of the maximum values along the third axis (depth level). The result is a 2D array where each element corresponds to the index of the maximum value in that depth slice.

3. **Element-wise Multiplication**:
   - **`random_array * random_array`** performs element-wise multiplication of the array with itself, resulting in a new array where each element is the square of the corresponding element in the original array.

Feel free to modify the values of \( w \), \( w_R \), and `shape` to suit your needs. Let me know if you have any questions or need further assistance!

#Q7- Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data typeƒ Also display the taPle attriPutes and data types of each column‚

To clean and transform the 'Phone' column in a sample dataset, you can use the Pandas library in Python. This process involves removing non-numeric characters from the phone numbers and converting the column to a numeric data type. Additionally, you can display the attributes and data types of each column in the DataFrame.

Here’s a step-by-step example:

### Example Code

```python
import pandas as pd

# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Phone': ['+1 (234) 567-8900', '987-654-3210', '(555) 123 4567']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Clean and transform the 'Phone' column
df['Phone'] = df['Phone'].replace(r'\D', '', regex=True).astype(float)

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

# Display attributes and data types of each column
print("\nDataFrame Info:")
print(df.info())
```

### Explanation

1. **Creating the DataFrame**: We first create a sample DataFrame with names and phone numbers.
  
2. **Cleaning the 'Phone' Column**:
   - **`replace(r'\D', '', regex=True)`**: This uses a regular expression to remove all non-numeric characters from the phone numbers.
   - **`astype(float)`**: Converts the cleaned phone numbers to a numeric data type. You can also use `astype(int)` if you prefer integers, but it will not work if there are any phone numbers with leading zeros.

3. **Displaying the Cleaned DataFrame**: Shows the DataFrame after the 'Phone' column has been cleaned.

4. **Displaying DataFrame Info**: The `info()` method provides information about the DataFrame, including the column names, non-null counts, and data types.

### Sample Output

```
Original DataFrame:
      Name               Phone
0    Alice   +1 (234) 567-8900
1      Bob        987-654-3210
2  Charlie        (555) 123 4567

Cleaned DataFrame:
      Name          Phone
0    Alice  12345678900.0
1      Bob    9876543210.0
2  Charlie    5551234567.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object
 1   Phone   3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 120.0 bytes
```

### Conclusion
This code cleans the 'Phone' column by removing all non-numeric characters and converting it to a numeric data type. The `info()` method provides a summary of the DataFrame, including the data types of each column. If you have any more questions or need further assistance, feel free to ask!

# Q8- Perform the following tas\s using people dataset:

 a) Read the 'dataYcsv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 valuesX

Sure! Here’s how to perform the specified tasks using a hypothetical `people.csv` dataset with the given requirements. This example will assume you have the `pandas` library installed and the `people.csv` file accessible.

### Example Code

```python
import pandas as pd

# a) Read the 'people.csv' file, skipping the first 50 rows
df = pd.read_csv('people.csv', skiprows=50)

# b) Only read the specified columns
filtered_df = df[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]

# c) Display the first 10 rows of the filtered dataset
print("First 10 rows of the filtered dataset:")
print(filtered_df.head(10))

# d) Extract the 'Salary' column as a Series and display its last 5 values
salary_series = filtered_df['Salary']
print("\nLast 5 values of the 'Salary' column:")
print(salary_series.tail(5))
```

### Explanation

1. **Reading the CSV File**:
   - **`pd.read_csv('people.csv', skiprows=50)`**: Reads the `people.csv` file while skipping the first 50 rows.

2. **Filtering Columns**:
   - **`df[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]`**: Selects only the specified columns from the DataFrame.

3. **Displaying the First 10 Rows**:
   - **`filtered_df.head(10)`**: Displays the first 10 rows of the filtered DataFrame.

4. **Extracting the 'Salary' Column**:
   - **`filtered_df['Salary']`**: Extracts the 'Salary' column as a Series.
   - **`salary_series.tail(5)`**: Displays the last 5 values of the 'Salary' Series.

### Note
Make sure to replace `'people.csv'` with the actual path to your CSV file. The actual structure of the dataset may vary, so ensure the column names match those in your file.

### Sample Output (Hypothetical)

```
First 10 rows of the filtered dataset:
     Last Name   Gender               Email              Phone   Salary
0       Smith     Male   smith@example.com   123-456-7890   50000
1       Johnson   Female johnson@example.com  234-567-8901   60000
2       Williams  Female williams@example.com  345-678-9012   70000
3       Brown     Male   brown@example.com   456-789-0123   55000
4       Jones     Female jones@example.com   567-890-1234   80000
5       Garcia    Male   garcia@example.com  678-901-2345   72000
6       Martinez  Female martinez@example.com 789-012-3456   62000
7       Davis     Male   davis@example.com   890-123-4567   52000
8       Rodriguez Female rodriguez@example.com  901-234-5678   91000
9       Wilson    Male   wilson@example.com   012-345-6789   64000

Last 5 values of the 'Salary' column:
5    72000
6    62000
7    52000
8    91000
9    64000
Name: Salary, dtype: int64
```

If you need any adjustments or have further questions, feel free to ask!

# Q9- Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Du\e', Gender' column contains the word Female and ‘Nalary’ should Pe less than _.RRR‚

To filter and select rows from a dataset (like `People_Dataset`) where the "Last Name" column contains "Duke," the "Gender" column contains "Female," and the "Salary" is less than a specified amount (let's say 80000 for this example), you can use the following code with the Pandas library.

### Example Code

```python
import pandas as pd

# Load the dataset
df = pd.read_csv('People_Dataset.csv')

# Specify the salary threshold
salary_threshold = 80000

# Filter the DataFrame
filtered_df = df[
    (df['Last Name'].str.contains('Duke', case=False, na=False)) &
    (df['Gender'].str.contains('Female', case=False, na=False)) &
    (df['Salary'] < salary_threshold)
]

# Display the filtered results
print("Filtered DataFrame:")
print(filtered_df)
```

### Explanation

1. **Loading the Dataset**:
   - **`pd.read_csv('People_Dataset.csv')`**: Loads the dataset into a DataFrame. Make sure to replace `'People_Dataset.csv'` with the actual path to your file.

2. **Filtering Conditions**:
   - **`df['Last Name'].str.contains('Duke', case=False, na=False)`**: Checks if the "Last Name" column contains the substring "Duke", ignoring case and handling any NaN values.
   - **`df['Gender'].str.contains('Female', case=False, na=False)`**: Checks if the "Gender" column contains "Female".
   - **`df['Salary'] < salary_threshold`**: Checks if the "Salary" is less than the specified threshold (80000 in this case).

3. **Combining Conditions**:
   - The `&` operator is used to combine all the conditions, ensuring that all must be true for a row to be included in the filtered DataFrame.

4. **Displaying the Filtered Results**:
   - The filtered DataFrame is printed to show only the rows that match the specified criteria.

### Sample Output (Hypothetical)
The output would look something like this (actual data will vary based on your dataset):

```
Filtered DataFrame:
    Last Name  Gender               Email              Phone  Salary
0        Duke  Female  duke@example.com    123-456-7890   75000
1        Duke  Female  duke2@example.com   234-567-8901   50000
```

If you have specific criteria for the salary or need further modifications, feel free to ask!

# Q10-Create a 7*. Dataframe in Pandas using a series generated from ‹. random integers Petween w to )?

To create a 7x7 DataFrame in Pandas using a Series generated from random integers between specific values, you'll need to use the `numpy` library for generating random integers and then construct the DataFrame from it. Here's a step-by-step guide to do that:

1. **Import the necessary libraries**: You'll need both `pandas` and `numpy`.
2. **Generate random integers**: Use `numpy.random.randint` to generate random integers between the specified range.
3. **Create a DataFrame**: Convert the generated Series of integers into a DataFrame.

Here's an example code snippet that accomplishes this:

```python
import pandas as pd
import numpy as np

# Set the range for random integers
low = 0  # Specify the lower bound
high = 10  # Specify the upper bound (exclusive)

# Generate a Series of random integers
random_integers = np.random.randint(low, high, size=(7, 7))

# Create a DataFrame from the random integers
df = pd.DataFrame(random_integers)

# Display the DataFrame
print(df)
```

### Explanation:
- Replace `low` and `high` with the desired integer limits for your random numbers.
- `size=(7, 7)` specifies that you want a 7x7 DataFrame.
- The resulting DataFrame `df` will contain random integers in the specified range.

Feel free to modify the `low` and `high` values to suit your needs!

#Q11- Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by 'oining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc&

To create the two Series and a DataFrame as you described, you can use the `pandas` library along with `numpy` for generating random numbers. Below is the code to achieve that:

```python
import pandas as pd
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Create the first Series with random numbers from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# Create the second Series with random numbers from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, size=50))

# Create a DataFrame by joining these Series by column
df = pd.DataFrame({
    'col1': series1,
    'col2': series2
})

# Display the DataFrame
print(df)
```

### Explanation:
1. **Import Libraries**: Import `pandas` for DataFrame creation and `numpy` for generating random numbers.
2. **Set Random Seed**: This ensures that the random numbers generated are the same each time the code runs (for reproducibility).
3. **Create Series**:
   - `series1` contains random integers between 10 and 50.
   - `series2` contains random integers between 100 and 1000.
4. **Create DataFrame**: Combine the two Series into a DataFrame with specified column names (`col1` and `col2`).
5. **Display the DataFrame**: Print the resulting DataFrame.

You can run this code in a Python environment where `pandas` and `numpy` are installed to see the results!

#Q12- Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final outut also&

To perform the specified operations on a people dataset using Python's `pandas` library, you can follow these steps. Here's an example of how you might do it:

```python
import pandas as pd

# Load your people dataset (replace 'people_data.csv' with your actual file)
# Example: df = pd.read_csv('people_data.csv')
# For demonstration, let's create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'dave@example.com'],
    'Phone': ['123-456-7890', '098-765-4321', None, '321-654-0987'],
    'Date of birth': ['1990-01-01', '1992-05-12', '1985-07-21', '1999-11-30'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Teacher']
}

df = pd.DataFrame(data)

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns
df.drop(columns=['Email', 'Phone', 'Date of birth'], inplace=True)

# b) Delete the rows containing any missing values
df.dropna(inplace=True)

# d) Print the final output
print(df)
```

### Explanation:
1. **Load the Dataset**: Replace the placeholder with the actual file path of your dataset. In this example, I created a sample DataFrame.
2. **Delete Columns**: Use `drop(columns=...)` to remove the specified columns from the DataFrame.
3. **Delete Rows with Missing Values**: Use `dropna()` to remove any rows that contain missing values.
4. **Print the Final Output**: Display the cleaned DataFrame.

### Output
When you run the above code, you will see a DataFrame printed that contains only the 'Name' and 'Occupation' columns with any rows containing missing values removed. If there were no rows left after the deletions, an empty DataFrame would be displayed.

#Q13- Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:

a) Create a scatter lot using x and y, setting the color of the oints to red and the marker style to 'o'.

b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

e) Set the title of the lot as 'Advanced Scatter Plot of Random Values'.

f) Dislay a legend for the scatter lot, the horizontal line, and the vertical line.

You can achieve the desired scatter plot and enhancements using the `matplotlib` library in combination with `numpy`. Here's how to create the plot based on your requirements:

```python
import numpy as np
import matplotlib.pyplot as plt

# Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o', label='Data Points')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Label the axes
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Set the title of the plot
plt.title('Advanced Scatter Plot of Random Values')

# Display a legend
plt.legend()

# Show the plot
plt.show()
```

### Explanation:
1. **Import Libraries**: Import `numpy` for generating random numbers and `matplotlib.pyplot` for plotting.
2. **Create Random Arrays**: Generate two arrays `x` and `y` filled with 100 random float values between 0 and 1.
3. **Scatter Plot**: Use `plt.scatter()` to create a scatter plot with red points ('o' markers).
4. **Horizontal Line**: Add a dashed horizontal line at `y = 0.5` using `plt.axhline()`.
5. **Vertical Line**: Add a dotted vertical line at `x = 0.5` using `plt.axvline()`.
6. **Axis Labels**: Label the x-axis and y-axis using `plt.xlabel()` and `plt.ylabel()`.
7. **Title**: Set the title of the plot with `plt.title()`.
8. **Legend**: Display a legend for the scatter plot and lines using `plt.legend()`.
9. **Show Plot**: Finally, use `plt.show()` to display the plot.

Running this code will give you a scatter plot with the specified enhancements.

#Q14- Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:
a) Plot the 'Temerature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the lot as 'Temerature and Humidity Over Time'.


Certainly! Let’s create a time-series dataset in a Pandas DataFrame with columns for 'Date', 'Temperature', and 'Humidity', and then visualize it using Matplotlib. Here’s how you can do it:

### Step 1: Create the Dataset

We’ll generate a sample dataset with dates, temperature, and humidity values.

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(0)

# Create a date range
dates = pd.date_range(start='2023-01-01', periods=100, freq='D')

# Generate random temperature and humidity data
temperature = np.random.normal(loc=20, scale=5, size=len(dates))  # Normal distribution around 20°C
humidity = np.random.uniform(low=30, high=80, size=len(dates))    # Uniform distribution between 30% and 80%

# Create DataFrame
data = pd.DataFrame({
    'Date': dates,
    'Temperature': temperature,
    'Humidity': humidity
})

# Display the first few rows of the dataset
print(data.head())
```

### Step 2: Visualize the Data

Now, we’ll create plots to visualize the temperature and humidity over time.

```python
# Set the Date column as the index
data.set_index('Date', inplace=True)

# Create a figure and axis
plt.figure(figsize=(14, 7))

# Plot temperature
plt.subplot(2, 1, 1)  # Two rows, one column, first subplot
plt.plot(data.index, data['Temperature'], color='orange', label='Temperature (°C)')
plt.title('Temperature Over Time')
plt.xlabel('Date')
plt.ylabel('Temperature (°C)')
plt.xticks(rotation=45)
plt.grid()
plt.legend()

# Plot humidity
plt.subplot(2, 1, 2)  # Two rows, one column, second subplot
plt.plot(data.index, data['Humidity'], color='blue', label='Humidity (%)')
plt.title('Humidity Over Time')
plt.xlabel('Date')
plt.ylabel('Humidity (%)')
plt.xticks(rotation=45)
plt.grid()
plt.legend()

# Adjust layout
plt.tight_layout()
plt.show()
```

### Explanation

1. **Creating the Dataset**:
   - We generate a date range of 100 days starting from January 1, 2023.
   - Random temperature values are generated from a normal distribution centered around 20°C with a standard deviation of 5.
   - Random humidity values are generated from a uniform distribution between 30% and 80%.

2. **Visualizing the Data**:
   - We plot two subplots: one for temperature and another for humidity.
   - Each subplot includes labels, titles, a grid, and a legend for clarity.

You can run the code in a Python environment with Pandas and Matplotlib installed, and it will create and visualize the dataset as specified. Let me know if you need any further modifications or explanations!

# Q15- Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:

a) Plot a histogram of the data with 30 bins.

b) Overlay a line lot reresenting the normal distribution's robability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the lot as 'Histogram with PDF Overlay'.

Sure! Here's how you can create a NumPy array containing samples from a normal distribution and then visualize the histogram along with the Probability Density Function (PDF) using Matplotlib.

### Step 1: Create the Data

First, we need to generate the data using NumPy.

```python
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)  # Mean = 0, Standard Deviation = 1
```

### Step 2: Plot the Histogram and PDF

Next, we can create the histogram and overlay the PDF.

```python
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

# Set up the histogram
plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', edgecolor='black')

# Overlay the normal distribution's PDF
xmin, xmax = plt.xlim()  # Get the current limits of x-axis
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of the normal distribution
plt.plot(x, p, 'k', linewidth=2)

# Labeling the axes and title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')

# Show the plot
plt.grid()
plt.show()
```

### Explanation

1. **Generating Data**:
   - We generate 1000 samples from a normal distribution with a mean (`loc`) of 0 and a standard deviation (`scale`) of 1.

2. **Plotting**:
   - We create a histogram of the data with 30 bins using `plt.hist()`. The `density=True` parameter normalizes the histogram so that the area under the histogram integrates to 1.
   - We calculate the PDF of the normal distribution using `scipy.stats.norm.pdf()` and overlay it on the histogram.
   - Finally, we label the x-axis and y-axis, set the title, and display the plot.

### Output

This code will generate a histogram of the normally distributed samples with a line overlay representing the normal distribution's PDF, complete with appropriate labels and title. You can run this code in any Python environment that supports NumPy and Matplotlib, and it will create the desired visualization. Let me know if you need further assistance!

#Q16- Set the title of the plot as 'Histogram with PDF Overlay'.

Here's the code snippet with the title correctly set as **"Histogram with PDF Overlay"**. You can run this complete code block to generate the histogram and overlay the Probability Density Function (PDF):

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Set random seed for reproducibility
np.random.seed(0)

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)  # Mean = 0, Standard Deviation = 1

# Set up the histogram
plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', edgecolor='black')

# Overlay the normal distribution's PDF
xmin, xmax = plt.xlim()  # Get the current limits of x-axis
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of the normal distribution
plt.plot(x, p, 'k', linewidth=2)

# Labeling the axes and title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')  # Set the title here

# Show the plot
plt.grid()
plt.show()
```

### Explanation of Key Parts

- **Title Setting**: The line `plt.title('Histogram with PDF Overlay')` sets the title of the plot as you requested.
- **PDF Overlay**: The normal distribution's PDF is overlaid on the histogram for comparison.
- **Histogram Configuration**: The histogram uses 30 bins and is normalized to represent probabilities.

Running this code will give you a clear visualization with the specified title. Let me know if you need any further changes or explanations!

# Q17- Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

To create a scatter plot using Seaborn that colors points based on their position relative to the origin (quadrants), you can follow the code snippet below:

```python
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(0)

# Create two random arrays
x = np.random.randn(100)
y = np.random.randn(100)

# Determine the quadrant for each point
def determine_quadrant(x, y):
    if x > 0 and y > 0:
        return 'Quadrant I'
    elif x < 0 and y > 0:
        return 'Quadrant II'
    elif x < 0 and y < 0:
        return 'Quadrant III'
    elif x > 0 and y < 0:
        return 'Quadrant IV'
    else:
        return 'Origin'

# Create a DataFrame
data = pd.DataFrame({'x': x, 'y': y})
data['Quadrant'] = data.apply(lambda row: determine_quadrant(row['x'], row['y']), axis=1)

# Create the scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='x', y='y', hue='Quadrant', palette='viridis', s=100)

# Add legend, labels, and title
plt.legend(title='Quadrants')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Quadrant-wise Scatter Plot')
plt.axhline(0, color='grey', lw=1)
plt.axvline(0, color='grey', lw=1)

# Show the plot
plt.show()
```

### Explanation:
1. **Libraries**: The code imports `numpy`, `pandas`, `seaborn`, and `matplotlib`.
2. **Random Data**: It generates two arrays of random numbers for the x and y coordinates.
3. **Quadrant Function**: A function determines the quadrant for each point based on its x and y values.
4. **DataFrame**: A Pandas DataFrame is created to hold the x, y, and quadrant data.
5. **Scatter Plot**: `seaborn.scatterplot` is used to create the scatter plot, with points colored based on their quadrant.
6. **Customization**: Axes are labeled, a title is set, and horizontal/vertical lines are added to indicate the axes.

Run this code in a Python environment with `numpy`, `pandas`, `seaborn`, and `matplotlib` installed. Let me know if you need any adjustments!

# Q18- With Bo+eh, plot a line chart of a sine wave function, add rid lines, label the axes, and set the title as 'Sine Wave Function'8

Here's how you can create a line chart of a sine wave function using `matplotlib`, complete with grid lines, labeled axes, and a title:

```python
import numpy as np
import matplotlib.pyplot as plt

# Create an array of x values from 0 to 2π
x = np.linspace(0, 2 * np.pi, 100)
# Calculate the sine of each x value
y = np.sin(x)

# Create the plot
plt.figure(figsize=(10, 5))
plt.plot(x, y, label='y = sin(x)', color='blue')

# Add grid lines
plt.grid(True)

# Label the axes
plt.xlabel('x (radians)')
plt.ylabel('y')

# Set the title
plt.title('Sine Wave Function')

# Show legend
plt.legend()

# Display the plot
plt.show()
```

### Key Components:
- **`numpy`** is used for creating an array of x values and calculating the sine.
- **`matplotlib.pyplot`** is the plotting library that generates the line chart.
- The plot is configured with grid lines, axis labels, and a title for clarity.

You can run this code in a Python environment with `numpy` and `matplotlib` installed. Let me know if you have any questions or need further assistance!

#Q19 Usin Bo+eh, enerate a bar chart of randomly enerated cateorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Cateorical Bar Chart'8

To generate a bar chart of randomly generated categorical data with color-coded bars based on their values and hover tooltips using `Bokeh`, you can use the following code:

```python
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
import numpy as np
import pandas as pd

# Generate random categorical data
categories = ['A', 'B', 'C', 'D', 'E']
values = np.random.randint(1, 20, size=len(categories))

# Create a DataFrame
data = pd.DataFrame({'Category': categories, 'Value': values})

# Create a ColumnDataSource
source = ColumnDataSource(data=data)

# Create a color mapping based on values
colors = ['#%02x%02x%02x' % (int(255 - (value * 12.75)), int(value * 12.75), 0) for value in values]

# Create a bar chart
p = figure(x_range=categories, height=400, title='Random Categorical Bar Chart', toolbar_location=None)
p.vbar(x='Category', top='Value', source=source, width=0.9, color=colors)

# Add hover tooltips
hover_tool = HoverTool()
hover_tool.tooltips = [("Category", "@Category"), ("Value", "@Value")]
p.add_tools(hover_tool)

# Label the axes
p.xaxis.axis_label = 'Categories'
p.yaxis.axis_label = 'Values'

# Show the plot
show(p)
```

### Explanation:
1. **Libraries**: The code uses `Bokeh` for plotting and `numpy` and `pandas` for data manipulation.
2. **Random Data**: It generates random integer values for each category.
3. **Data Source**: A `ColumnDataSource` is created to hold the data for plotting.
4. **Color Mapping**: Colors are assigned to each bar based on their values for visual differentiation.
5. **Bar Chart**: A vertical bar chart is created using the `vbar` method.
6. **Hover Tooltips**: Tooltips are added to display the category and value when hovering over the bars.
7. **Axes Labels and Title**: The axes are labeled, and a title is set for the chart.

You can run this code in a Python environment with `Bokeh` installed. Make sure to enable the appropriate output mode (like `output_notebook()` for Jupyter or `output_file()` for standalone HTML files) as needed. Let me know if you need any adjustments!

#Q20- Usin Plotly, create a basic line plot of a randomly enerated dataset, label the axes, and set the title as 'Simple Line Plot'8

To create a basic line plot using Plotly with a randomly generated dataset, you can use the following code:

```python
import plotly.graph_objs as go
import numpy as np

# Generate random data
x = np.linspace(0, 10, 100)  # X values
y = np.random.rand(100)  # Y values

# Create the line plot
fig = go.Figure()

fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='Random Data'))

# Label the axes and set the title
fig.update_layout(
    title='Simple Line Plot',
    xaxis_title='X-axis',
    yaxis_title='Y-axis'
)

# Show the plot
fig.show()
```

### Explanation:
1. **Libraries**: The code uses `plotly.graph_objs` for creating the plot and `numpy` for generating random data.
2. **Random Data**: It generates 100 x-values ranging from 0 to 10 and 100 random y-values.
3. **Line Plot**: A `Scatter` plot is created in line mode.
4. **Layout**: The axes are labeled, and a title is set for the plot.
5. **Display**: Finally, the plot is displayed using `fig.show()`.

You can run this code in a Python environment with Plotly installed. If you're using Jupyter Notebook, you may also want to enable the inline display with `plotly.offline.init_notebook_mode()`. Let me know if you need any further adjustments!

# Q21 Usin Plotly, create an interactive pie chart of randomly enerated data, add labels and percentaes, set the title as 'Interactive Pie Chart'.

To create an interactive pie chart using Plotly with randomly generated data, you can use the following code:

```python
import plotly.graph_objs as go
import numpy as np

# Generate random data
labels = ['Category A', 'Category B', 'Category C', 'Category D']
values = np.random.randint(1, 100, size=len(labels))

# Create the pie chart
fig = go.Figure(data=[go.Pie(labels=labels, values=values,
                               textinfo='label+percent',
                               hole=0.3)])  # Optional: for a donut chart, set hole > 0

# Set the title
fig.update_layout(title='Interactive Pie Chart')

# Show the plot
fig.show()
```

### Explanation:
1. **Libraries**: The code uses `plotly.graph_objs` for creating the plot and `numpy` for generating random data.
2. **Random Data**: It generates random integer values for each category.
3. **Pie Chart**: A `Pie` chart is created with labels and values, and the `textinfo` parameter is set to display both labels and percentages.
4. **Title**: The chart title is set using `update_layout`.
5. **Display**: Finally, the plot is displayed using `fig.show()`.

You can run this code in a Python environment with Plotly installed. Let me know if you need any further modifications or explanations!